### ISSUE TITLE
Test framework quit unexpectedly on version 1.4

### ISSUE THREAD

**Issue by StanislavGrishaev** [APshenkin/intellij-codeceptjs#5]
**Describe the bug**

For some reason, not one of the tests on the current version 1.4 is launched (there is no such problem on version 1.2)
- Click on play from the test
- The startup process almost instantly ends with code 0 (see screenshots)

**an interesting point** - if you run the entire file with tests - there is no problem, in my opinion there is some kind of problem with searching for a specific test by name using the --grep flag

**Versions**:
- Plugin: 1.4
- IDE: GoLand 2023.1
- OS: macOS Monterey
- codeceptjs: 3.3.7
- NodeJS: 18.12.1

**Screenshots**:

Test : 
![image](https://user-images.githubusercontent.com/115224622/230074998-cd62fbcd-6663-47d3-9ca8-223cc1cb6114.png)
Output : 
![image](https://user-images.githubusercontent.com/115224622/230075056-ccbcfac9-815f-45df-801c-b55e2aace98d.png)
Running configuration : 
![image](https://user-images.githubusercontent.com/115224622/230075137-2469c1c2-1806-4c51-bcd5-c1b2d7f8e82d.png)
![image](https://user-images.githubusercontent.com/115224622/230075150-161262e3-a0d3-484a-a2df-c54fce55249c.png)

**Comment by StanislavGrishaev** [comment]
alright, as far as I can see, if you do not use the caret symbol, then the test is successfully found, with it - no, in the screenshot there is an example of launching without caret (successful) and an example of launching the way the plugin does it (not successful) - 
![image](https://user-images.githubusercontent.com/115224622/230128913-b00ab48a-b56e-428b-ac70-59ac3a25e97d.png)

**Comment by APshenkin** [comment]
@StasGrishaevTutu sorry for long reply.

So caret `^` as well as `$` in the end are used to actually avoid cases, when test cases have same names like

```
Scenario('foo', async () => {})
Scenario('foo bar', async () => {})
```

grep condition is specified as concatenation of `Feature` name + `Scenario` name

My bet is that you are not specifying `Feature('something')` before the tests. It should be something like
```
Feature('my tests')
Scenario('foo', async () => {})
Scenario('foo bar', async () => {})
```

I can reproduce this error in case, when `Feature` is not specified.

I think problem is related with this line https://github.com/APshenkin/intellij-codeceptjs/blob/master/src/main/kotlin/com/apshenkin/codeceptjs/run/CodeceptjsRunState.kt#L117

It's required to identify, what is the full name of test name, when `Feature` is not specified to pass proper grep then

Edited:
So in case, when `Feature` is not specified, the full name that Mocha is using is
```
: Download confirmation document
```

As only Scenario is passed.
In plugin we try to reproduce it using:
```
data.allNames ->>> it.joinToString(separator = ": ")
```
But as there is a list with single element, it doesn't put leading `: ` in that case.

**Comment by StanislavGrishaev** [comment]
@APshenkin thanks for investigating, but some time ago i migrated to pure Playwright, anyway thanks for you plugin ! I will close the issue.
